title: DbBot
logo: https://gitlab.com/uploads/-/system/project/avatar/6696596/photo_2016-09-16_06-28-14.jpg
description: Robot Db version 1.0 is a simple bot made to run on the android and the terminal and has its structure made by telepot lib.
show_downloads: True
google_analytics:
theme: jekyll-theme-minimal
